### ISSUE TITLE
 program version required (Commander::Runner::CommandError)

### ISSUE THREAD

**Issue by TangMonk** [icyleaf/xiaomi-push#1]
If I run with following command:

```
xmp message --device android --secret '********' -i 'biao' -d 'adasd'
```

will throw error:

```
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/runner.rb:391:in `block in require_program': program version required (Commander::Runner::CommandError)
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/runner.rb:390:in `each'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/runner.rb:390:in `require_program'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/runner.rb:52:in `run!'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/import.rb:5:in `block in <top (required)>'
/Users/tangmonk/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- dotenv (LoadError)
    from /Users/tangmonk/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:121:in `require'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/xiaomi-push-0.2.1/lib/xiaomi/push.rb:15:in `<top (required)>'
    from /Users/tangmonk/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/tangmonk/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/xiaomi-push-0.2.1/bin/xmp:6:in `<top (required)>'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/bin/xmp:23:in `load'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/bin/xmp:23:in `<main>'
```

**Comment by icyleaf** [comment]
Thanks for report issue, i updated code, please update the laster version `0.2.3`.

```
$ gem update xiaomi-push
$ gem cleanup xiaomi-push
```

please report again if there still trouble.

**Comment by TangMonk** [comment]
@lcyleaf , 多谢

但是我看了文档里加了一句话:

> 小米官方好像也就不怎么维护此服务，本 gem 除了修复问题以为不做新特性的更新。

小米官方遗弃了这个项目吗？

**Comment by icyleaf** [comment]
好像是不会投入太多精力在这个项目上面了，一些反馈跟进也很缓慢。

我先关闭问题，如果还有问题重新 reopen

**Comment by TangMonk** [comment]
好的，多谢
