### ISSUE TITLE
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- dotenv (LoadError)

### ISSUE THREAD

**Issue by TangMonk** [icyleaf/xiaomi-push#2]
和rails 的gemfile 一起安装，之后运行rails s会报错如下：

```
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- dotenv (LoadError)
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/xiaomi-push-0.2.3/lib/xiaomi/push.rb:14:in `<top (required)>'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.3/lib/bundler/runtime.rb:85:in `require'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.3/lib/bundler/runtime.rb:85:in `rescue in block in require'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.3/lib/bundler/runtime.rb:68:in `block in require'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.3/lib/bundler/runtime.rb:61:in `each'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.3/lib/bundler/runtime.rb:61:in `require'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.3/lib/bundler.rb:134:in `require'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/zeus-0.15.4/lib/zeus/rails.rb:97:in `default_bundle'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/zeus-0.15.4/lib/zeus.rb:200:in `run_action'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/zeus-0.15.4/lib/zeus.rb:74:in `block (2 levels) in boot_steps'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/zeus-0.15.4/lib/zeus/load_tracking.rb:7:in `features_loaded_by'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/zeus-0.15.4/lib/zeus.rb:73:in `block in boot_steps'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/zeus-0.15.4/lib/zeus.rb:56:in `catch'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/zeus-0.15.4/lib/zeus.rb:56:in `boot_steps'
    from /Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/zeus-0.15.4/lib/zeus.rb:48:in `go'
```

需要手动加入 'dotenv' 到gemfile里

**Comment by icyleaf** [comment]
我来检查下， dotenv 是以调试并检查是否存在的方式存在的，按理说不应该会有这样的报错

**Comment by icyleaf** [comment]
已修正，升级下版本号至 0.2.4

**Comment by TangMonk** [comment]
多谢
